version: '3'
services:
  db:
    image: postgres:13
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data/pgdata
    networks: 
     - frontend

  odoo14:
    image: odoo:14.0
    depends_on:
      - db
    links:
      - db
    ports:
      - "8069:8069"
    tty: true
    # command: --dev=all
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./data:/var/lib/odoo
      - .:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: always             # run as a service
    networks: 
     - frontend
    
networks:
 frontend:
